config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  get 'users/show'
  # ルーティングをusers/registrationにしてコントローラーをカスタマイズできるようにする記述
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :tweets do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :likes_count
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user

    validates :name, :text, :video, presence: true

    mount_uploader :video, VideoUploader

    has_many :comments, dependent: :destroy

    has_many :likes, dependent: :destroy

    def like_user(user_id)
      likes.find_by(user_id: user_id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true, uniqueness: true
  validates :image, presence: true
  
  has_many :tweets, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  #フォロワー取得
  has_many :following_user, through: :follower, source: :followed  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower  # 自分をフォローしている人

  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # 検索機能
  def self.search(search)
    if search != ""
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image, :text])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :image, :text])
  end

  def after_sign_in_path_for(resource)
    flash[:notice] = "ログインしました"
    tweets_path
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      render tweet_path(@comment.tweet.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
    
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload 
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    like.destroy
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload
  end

  private

  def set_post
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_to user_path
  end
  
  def unfollow
    current_user.unfollow(params[:id])
    redirect_to user_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  def index
    @tweets = Tweet.includes(:user)
    @tweets = @tweets.where(user_id: [current_user.id, *current_user.following_user]).order(created_at: :desc)
    @image = current_user.image
    @nickname = current_user.nickname
    @user = User.where(params[:id])
  end

  def new
    @tweet = Tweet.new
    # tweet = Tweet.find(params[:id])
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "投稿しました。"
    else
      flash[:alert] = @tweet.errors.full_messages.join(',')
      render :new        
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    # tweet.update(tweet_params)

    if tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ツイートが更新されました。"
    else
      flash[:alert] = tweet.errors.full_messages.join(',')
      redirect_to edit_tweet_path        
    end

  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :video, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    # @user = User.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @image = current_user.image
    @tweets = Tweet.where(user_id: @user.id).order(created_at: :desc)
    @count = @tweets.count
    @users = @user.follower.all
    @following_user = current_user.following_user
    @follower_user = current_user.follower_user

  end
  
  def search
    @users = User.search(params[:keyword])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.haml
- unless tweet.like_user(current_user.id).blank?
  = link_to tweet_like_path(tweet_id: tweet.id, id: tweet.likes[0].id), method: :delete, remote: true do
    .vertical_like
      %i.fas.fa-heart.unlike-btn
      .unlike
        = tweet.likes_count
        人が『いいね』しました
- else
  = link_to tweet_likes_path(tweet.id), method: :post, remote: true do
    .vertical_like
      %i.far.fa-heart.like-btn
      .like
        = tweet.likes_count
        人が『いいね』しました

app/views/likes/create.html.haml
%h1 Likes#create
%p Find me in app/views/likes/create.html.haml

app/views/likes/create.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'like', locals: { tweet: @tweet }) %>");

app/views/likes/destroy.html.haml
%h1 Likes#destroy
%p Find me in app/views/likes/destroy.html.haml

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'likes/like', locals: {tweet: @tweet}) %>");

app/views/tweets/create.html.haml
.contents
  .success
    %h3.success-text 投稿が完了しました。
    %a.success-button(href="/tweets")投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.contents
  .success
    %h3.success-text 削除が完了しました。
    %a.success-button(href="/tweets")投稿一覧へ戻る

app/views/tweets/edit.html.haml
.contents.row
  .container
    %h3.new_title 編集 
    = form_with model: @tweet, html: { class: "form" }, local: true do |f|
      .input 
        %span.tweet-form-require 必須
        = f.text_field :name, placeholder: "メニュー名", class: 'title'
        %span.tweet-form-require 必須
        = f.text_area :text, placeholder: "メニュー内容", class: 'textarea'
      = f.label :video, for: "upload-image", class: 'image' do
        %span.tweet-form-require 必須
        %i.far.fa-image.img-sel
          動画を変更する
        = f.file_field :video, class: 'img-video', id: "upload-image"
      .img-img
        = video_tag @tweet.video_url, controls: true, style:"width:300px", class:"select img-preview"
      .submit
        = f.submit '投稿する', class: 'submit_list'

app/views/tweets/index.html.haml
-# = flash[:notice]
.contents.row
  .search
    = render "users/user-search"

  .scroll
    - @tweets.each do |tweet|
      -# .content_post{:style => "background-image: url(#{tweet.image});"}
      .content_tweet
        .content_tweet__header
          .content_tweet__header__right
            = link_to image_tag(tweet.user.image.to_s, class:"content_tweet__header__right__image"), user_path(tweet.user.id)
            .content_tweet__header__right__nickname
              = tweet.user.nickname
          .content_tweet__header__other
            -# 後でここにif文を記述 自身のツイートの場合表示、違う場合はコメント
            %ul.menu
              %li
                %i.fas.fa-bars
                - if user_signed_in? && current_user.id == tweet.user_id
                  %ul
                    %li
                      = link_to '詳細', tweet_path(tweet.id)
                    %li
                      = link_to '編集', edit_tweet_path(tweet.id), method: :get
                    %li
                      = link_to '削除', tweet_path(tweet.id), method: :delete
                - else
                  %ul
                    %li
                      = link_to '詳細', tweet_path(tweet.id), class:""

        .content_post
          = video_tag tweet.video.url, controls: true, class:"content_post__image"
        .content_like
          %span#likes_buttons{ id: tweet.id}
            = render partial: 'likes/like', locals: { tweet: tweet, likes: @likes}

        .content_text
          %span.name
            トレーニング名：
            = tweet.name
          %span.text 
            トレーニング内容： 
            = tweet.text
          .content_time
            投稿日：
            = tweet.created_at.strftime("%Y-%m-%d %H:%M")
            

app/views/tweets/new.html.haml
.contents.row
  .container
    %h3.new_title 投稿する
    = form_with model: @tweet, html: { class: "form" }, local: true do |f|
      .input 
        %span.tweet-form-require 必須
        = f.text_field :name, placeholder: "メニュー名", class: 'title'
        %span.tweet-form-require 必須
        = f.text_area :text, placeholder: "メニュー内容", class: 'textarea'
      = f.label :video, for: "upload-image", class: 'image' do
        %span.tweet-form-require 必須
        %i.far.fa-image.img-sel
          動画を選択する
        = f.file_field :video, class: 'img-video', id: "upload-image"
      .img-img
      .submit
        = f.submit '投稿する', class: 'submit_list'

app/views/tweets/show.html.haml
.show-page
  .show-page__container
    .show-page__container__header
      %h1.show-page__container__header__text 詳細ページ
    .show-page__container__main
      .show-page__container__main__image
        = video_tag @tweet.video.to_s, controls: true, class:"show-page__container__main__image__images"
      .show-page__container__main__like
        %span#likes_buttons{ id: @tweet.id}
          = render partial: 'likes/like', locals: { tweet: @tweet, likes: @likes}

      .show-page__container__main__text
        .show-page__container__main__text__lists
          %h2 トレーニング名：#{@tweet.name}
        .show-page__container__main__text__lists
          %h2 トレーニング内容：#{@tweet.text}
        .show-page_time
          投稿日：
          = @tweet.created_at.strftime("%Y-%m-%d %H:%M")
      .show-page__container__main__comments
        .show-page__container__main__comments__lists
          %h4.show-page__container__main__comments__lists__list コメント一覧
          .show-page__container__main__comments__lists__main
            - @comments.each do |comment|
              .show-page__container__main__comments__lists__main__link
                .show-page__container__main__comments__lists__main__link__left
                  %strong
                    = link_to "#{comment.user.nickname} :", "/users/#{comment.user_id}", class:"show-page__container__main__comments__lists__main__link__left__a"
                  = comment.text
                .show-page__container__main__comments__lists__main__link__right
                  = comment.created_at.strftime("%Y-%m-%d %H:%M")

        .show-page__container__main__comments__form
          - if user_signed_in?
            = form_with model: [@tweet, @comment], local: true, id: "new_comment", remote: true do |f|
              = f.text_area :text, placeholder: "コメントを追加", rows: "2", class:"show-page__container__main__comments__form__textarea"
              = button_tag type: 'submit', class: "show-page__container__main__comments__form__submit" do
                %i.fas.fa-paper-plane
          - else
            %strong
              %p ＊＊＊コメントの投稿には新規登録/ログインが必要です＊＊＊

    

app/views/tweets/update.html.haml
.contents
  .success
    %h3.success-text 編集が完了しました。
    %a.success-button(href="/tweets")投稿一覧へ戻る