config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  get 'users/show'
  # ルーティングをusers/registrationにしてコントローラーをカスタマイズできるようにする記述
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :tweets do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true, uniqueness: true
  validates :image, presence: true
  
  has_many :tweets, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  #フォロワー取得
  has_many :following_user, through: :follower, source: :followed  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower  # 自分をフォローしている人

  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # 検索機能
  def self.search(search)
    if search != ""
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    # @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  def after_update_path_for(resource)
    user_path(current_user.id)
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   @user = User.new
  # end

  # POST /resource/sign_in
  # def create
  #   @user = User.new(sign_in_params)
  #   unless @user.valid?
  #     redirect_to 
  #   end
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @image = current_user.image
    @tweets = Tweet.where(user_id: @user.id).order(created_at: :desc)
    @count = @tweets.count
    @users = @user.follower.all
    @following_user = current_user.following_user
    @follower_user = current_user.follower_user

  end
  
  def search
    @users = User.search(params[:keyword])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow-button.html.haml
- unless current_user.following?(user)
  = link_to "フォローする", follow_path(user.id), method: :POST, class: "follow-black", remote: true
- else
  = link_to "フォロー中", unfollow_path(user.id), method: :POST, class: "followed-black", remote: true

app/views/users/_follow-buttons.html.haml
- if user == current_user
  = link_to "", "#"
- else
  - unless current_user.following?(user)
    = link_to "フォローする", follow_path(user.id), method: :POST, class: "follow-black",id: "follower-modal", remote: true
  - else
    = link_to "フォロー中", unfollow_path(user.id), method: :POST, class: "followed-black",id: "followed-modal", remote: true

app/views/users/_user-search.html.haml
.search
  = form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |f|
    = f.text_field :keyword, placeholder: "ユーザー検索", class: "search__form"
    = button_tag type: 'submit', class: "search__submit" do
      %i.fas.fa-search

app/views/users/follow.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render partial: 'users/follow-button',locals: { user: @user }) %>");
$("#follow-buttons_<%= user.id %>").html("<%= j(render partial: 'users/follow-buttons',locals: { user: user }) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followed.count }フォロワー", users_follower_path(@user) %>');
$("#followed-count_<%= current_user.id %>").html('<%= link_to "#{ current_user.follower.count }フォロー中", users_following_path(@user) %>');

app/views/users/search.html.haml
.search-container
  .search
    = render "user-search"
  .search-scroll
    - @users.each do |user|
      .search__list
        = link_to image_tag(user.image.to_s, class:"search__list__image"), user_path(user.id)
        .search__list__name
          = user.nickname

              

app/views/users/show.html.haml
.mypage
  .search
    = render "user-search"
  .mypage__container
    .mypage__container__header
      .mypage__container__header__picture
        = image_tag @user.image.to_s, class: "mypage__container__header__picture__image"
      .mypage__container__header__main
        .mypage__container__header__main__name
          = @user.nickname
          - unless @user == current_user
            %span#follow_button_{ id: @user.id}
              = render "users/follow-button", user: @user
          - else
            = link_to "設定", edit_user_registration_path, class:"follow-black"
        %ul.mypage__container__header__main__lists
          %li.mypage__container__header__main__lists__list 投稿#{@count}件
          %li.mypage__container__header__main__lists__list.follower_modal_content#follower-count_{ id: @user.id} フォロー#{@user.follower.count}人
          %li.mypage__container__header__main__lists__list.followed_modal_content#followed-count_{ id: @user.id} フォロワー#{@user.followed.count}人
        .mypage__container__header__main__text
          コメント：
          = @user.text
        

    -# ヘッダー部分
    .mypage__container__main
      .mypage__container__main__image
        - @tweets.each do |tweet|
          %section.image-image
            = link_to video_tag(tweet.video.url, controls: true, class:"mypage__container__main__image__images"), tweet_path(tweet.id)
            .mypage__container__main__image__name
              %p トレーニング名： #{tweet.name}
            .mypage__container__main__image__text
              %p トレーニング内容： #{tweet.text}

-# フォロワーモーダル表示         
.followed_modal_wrapper
.followed_modal
  %i.fa.fa-2x.fa-times
  .followed_modal__container
    .followed_modal__container__header
      .followed_modal__container__header__name フォロワー
    .followed_modal__container__main
      - @user.follower_user.each do |user|
        .followed_modal__container__main__list
          .followed_modal__container__main__list__lists
            = link_to image_tag(user.image.to_s, class:"followed_modal__container__main__list__lists__image"), user_path(user.id)
            .followed_modal__container__main__list__lists__name
              = user.nickname
          .followed_modal__container__main__list__follow
            %span#follow-buttons_{ id: user.id}
              = render "users/follow-buttons", user: user
            -# - if user == current_user
            -#   = link_to "", "#"
            -# - else
            -#   - unless current_user.following?(user)
            -#     = link_to "フォローする", follow_path(user.id), method: :POST, class: "follow-black"
            -#   - else
            -#     = link_to "フォロー中", unfollow_path(user.id), method: :POST, class: "follow-black"

-# フォローモーダル表示         
.follower_modal_wrapper
.follower_modal
  %i.fa.fa-2x.fa-times
  .follower_modal__container
    .follower_modal__container__header
      .follower_modal__container__header__name フォロー
    .follower_modal__container__main
      - @user.following_user.each do |user|
        .follower_modal__container__main__list
          .follower_modal__container__main__list__lists
            = link_to image_tag(user.image.to_s, class:"followed_modal__container__main__list__lists__image"), user_path(user.id)
            .follower_modal__container__main__list__lists__name
              = user.nickname
          .follower_modal__container__main__list__follow
            %span#follow-buttons_{ id: user.id}
              = render "users/follow-buttons", user: user

            -# - if user == current_user
            -#   = link_to "", "#"
            -# - else
            -#   - unless current_user.following?(user)
            -#     = link_to "フォローする", follow_path(user.id), method: :POST, class: "follow-black"
            -#   - else
            -#     = link_to "フォロー中", unfollow_path(user.id), method: :POST, class: "follow-black"
        

    
    

app/views/users/unfollow.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render partial: 'users/follow-button',locals: { user: @user }) %>");
$("#follow-buttons_<%= user.id %>").html("<%= j(render partial: 'users/follow-buttons',locals: { user: user }) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followed.count }フォロワー", users_follower_path(@user) %>');
$("#followed-count_<%= current_user.id %>").html('<%= link_to "#{ current_user.follower.count }フォロー中", users_following_path(@user) %>');