config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  get 'users/show'
  # ルーティングをusers/registrationにしてコントローラーをカスタマイズできるようにする記述
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :tweets do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :likes_count
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user

    validates :name, :text, :video, presence: true

    mount_uploader :video, VideoUploader

    has_many :comments, dependent: :destroy

    has_many :likes, dependent: :destroy

    def like_user(user_id)
      likes.find_by(user_id: user_id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true, uniqueness: true
  validates :image, presence: true
  
  has_many :tweets, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy  #フォロワー取得
  has_many :following_user, through: :follower, source: :followed  # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower  # 自分をフォローしている人

  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  # 検索機能
  def self.search(search)
    if search != ""
      User.where('nickname LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      render tweet_path(@comment.tweet.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
    
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload 
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    like.destroy
    @likes = Like.where(tweet_id: params[:tweet_id])
    @tweet.reload
  end

  private

  def set_post
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  def index
    @tweets = Tweet.includes(:user)
    @tweets = @tweets.where(user_id: [current_user.id, *current_user.following_user]).order(created_at: :desc)
    @image = current_user.image
    @nickname = current_user.nickname
    @user = User.where(params[:id])
  end

  def new
    @tweet = Tweet.new
    # tweet = Tweet.find(params[:id])
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "投稿しました。"
    else
      flash[:alert] = @tweet.errors.full_messages.join(',')
      render :new        
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    # tweet.update(tweet_params)

    if tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ツイートが更新されました。"
    else
      flash[:alert] = tweet.errors.full_messages.join(',')
      redirect_to edit_tweet_path        
    end

  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :video, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    # @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @image = current_user.image
    @tweets = Tweet.where(user_id: @user.id).order(created_at: :desc)
    @count = @tweets.count
    @users = @user.follower.all
    @following_user = current_user.following_user
    @follower_user = current_user.follower_user

  end
  
  def search
    @users = User.search(params[:keyword])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Musclebot
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .flash-alert
      = flash[:alert]
    .flash-notice
      = flash[:notice]
    .Header
      .Header__container
        .Header__log
          - if user_signed_in?
            = link_to "MuscleBot", root_path, class:"musclebot-title"
          - else
            = link_to "MuscleBot", '#', class: "sign_modal_content"
        .Header__lists
          - if user_signed_in?
            %ul
              %li.Header__list
                = link_to "閲覧ページ", tweets_path
              %li.Header__list
                = link_to "投稿する", new_tweet_path
              %li.Header__list
                = link_to "マイページ", user_path(current_user.id)
              %li.Header__list
                = link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？'}
          - else
            %ul
              %li.Header__list#login-page
                = link_to "ログイン", new_user_session_path, class: "sign_modal_content"
              %li.Header__list
                = link_to "新規登録", new_user_registration_path
    = yield
    %footer
      %p Copyright MuscleBot 2020.
      

app/views/layouts/posts.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Musclebot
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    = yield
    